DECLARE

  fecha VARCHAR2(10);
BEGIN

  SELECT TO_CHAR(MAX(FEC_HOY), 'DDMMYYYY')
  INTO fecha
  FROM CALENDARIOS
  WHERE COD_SISTEMA = 'TC';


  UPDATE CALENDARIOS
  SET FEC_HOY = TO_DATE(fecha, 'DD/MM/YYYY'), 
      NOM_DIA = CALENDAR.DIA_DE_LA_SEMANA(TO_DATE(fecha, 'DD/MM/YYYY'), 'SPANISH'), 
      FEC_ANTERIOR = CALENDAR.OBTENER_ANT_FEC_HABIL('1','10401',TO_DATE(fecha, 'DD/MM/YYYY')), 
      PROX_FECHA = CALENDAR.OBTENER_SIG_FEC_HABIL('1','10401', TO_DATE(fecha, 'DD/MM/YYYY')), 
      PRIMER_DIA_MES = TO_DATE('01-' || TO_CHAR(TO_DATE(fecha, 'DD/MM/YYYY'), 'MON-YYYY')), 
      PRIMER_HABIL_MES = CALENDAR.OBTENER_PRIMER_HABIL_MES('1','10401', TO_DATE(fecha, 'DD/MM/YYYY')), 
      ULTIMO_DIA_MES = LAST_DAY(TO_DATE(fecha, 'DD/MM/YYYY')), 
      ULTIMO_HABIL_MES = CALENDAR.OBTENER_ULTIMO_HABIL_MES('1','10401', TO_DATE(fecha, 'DD/MM/YYYY'))
  WHERE COD_EMPRESA = '1'
    AND COD_SISTEMA = 'CD';


  UPDATE CALENDARIO
  SET FECHA_HOY = TO_DATE(fecha, 'DD/MM/YYYY'), 
      NOMBRE_DIA = CALENDAR.DIA_DE_LA_SEMANA(TO_DATE(fecha, 'DD/MM/YYYY'), 'SPANISH'), 
      FECHA_ANTERIOR = CALENDAR.OBTENER_ANT_FEC_HABIL('1','10401',TO_DATE(fecha, 'DD/MM/YYYY')), 
      PROXIMA_FECHA = CALENDAR.OBTENER_SIG_FEC_HABIL('1','10401', TO_DATE(fecha, 'DD/MM/YYYY')), 
      PRIMER_DIA_MES = TO_DATE('01-' || TO_CHAR(TO_DATE(fecha, 'DD/MM/YYYY'), 'MON-YYYY')), 
      PRIMER_HABIL_MES = CALENDAR.OBTENER_PRIMER_HABIL_MES('1','10401', TO_DATE(fecha, 'DD/MM/YYYY')), 
      ULTIMO_DIA_MES = LAST_DAY(TO_DATE(fecha, 'DD/MM/YYYY')), 
      ULTIMO_HABIL_MES = CALENDAR.OBTENER_ULTIMO_HABIL_MES('1','10401', TO_DATE(fecha, 'DD/MM/YYYY'))
  WHERE CODIGO_EMPRESA = '1'
    AND CODIGO_APLICACION = 'PR';

  COMMIT;
END;

