UPDATE INTERFACES_EXTERNAS_B2000 
SET CODIGO_VALIDACION = (
  SELECT TO_CHAR(MAX(FEC_HOY-1), 'DDMMYYYY')
  FROM CALENDARIOS WHERE COD_SISTEMA= 'CC' 
)
WHERE COD_SISTEMA ='BTC' 
AND NOMBRE_PROGRAMA='TCCARMTI'
