UPDATE CIERRE_X_GRUPOS
SET FEC_CIERRE_DIA = (
        SELECT TO_CHAR(MAX(FEC_HOY), 'DD-MONTH-YYYY', 'NLS_DATE_LANGUAGE=ENGLISH')
        FROM CALENDARIOS
        WHERE COD_SISTEMA = 'CC'
    ),
    PROCESO_DIA = 'PROCESO_COOP'
WHERE COD_EMPRESA = 1
  AND COD_GRUPO = 1
